#!/bin/bash

gnome-terminal -- bash -c "./start-gregistry; exec bash" &

sleep 2

gnome-terminal -- bash -c "./start-cyclicbarrier; exec bash" &

sleep 2

gnome-terminal -- bash -c "./start-dcvm GROUP_A_JVM; exec bash" &
gnome-terminal -- bash -c "./start-dcvm GROUP_B_JVM; exec bash" &
gnome-terminal -- bash -c "./start-dcvm GROUP_C_JVM; exec bash" &
