#!/bin/bash

gnome-terminal -- bash -c "./start-gregistry; exec bash" &

sleep 2

gnome-terminal -- bash -c "./start-cyclicbarrier; exec bash" &

sleep 2

gnome-terminal -- bash -c "./start-dcvm FRANCE_JVM; exec bash" &
gnome-terminal -- bash -c "./start-dcvm CANADA_JVM; exec bash" &
gnome-terminal -- bash -c "./start-dcvm BELGIUM_JVM; exec bash" &
